pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/your-repo.git'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                sh 'terraform init'
                sh 'terraform apply -auto-approve'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook -i inventory install_elasticsearch.yml'
            }
        }

        stage('Test Elasticsearch') {
            steps {
                sh 'curl -X GET "http://<Elasticsearch-IP>:9200/_cluster/health?pretty"'
            }
        }
    }
}

